### ISSUE TITLE
Encoding, an rtMessage structure types are incorrect

### ISSUE THREAD

**Issue by schmidtw** [rdkcentral/rbus#136]
The following values are not encoded as uint values, but are being encoded as signed integers.

- `sequence_number`: https://github.com/rdkcentral/rbus/blob/6455fb817e86a4cf42ddc3af482417dfc668b3c4/src/rtmessage/rtMessageHeader.c#L69
- `flags`: https://github.com/rdkcentral/rbus/blob/6455fb817e86a4cf42ddc3af482417dfc668b3c4/src/rtmessage/rtMessageHeader.c#L70
- `control_data`: https://github.com/rdkcentral/rbus/blob/6455fb817e86a4cf42ddc3af482417dfc668b3c4/src/rtmessage/rtMessageHeader.c#L71
- `payload_length`: https://github.com/rdkcentral/rbus/blob/6455fb817e86a4cf42ddc3af482417dfc668b3c4/src/rtmessage/rtMessageHeader.c#L72
- `T0`: https://github.com/rdkcentral/rbus/blob/6455fb817e86a4cf42ddc3af482417dfc668b3c4/src/rtmessage/rtMessageHeader.c#L76
- `T1`: https://github.com/rdkcentral/rbus/blob/6455fb817e86a4cf42ddc3af482417dfc668b3c4/src/rtmessage/rtMessageHeader.c#L77
- `T2`: https://github.com/rdkcentral/rbus/blob/6455fb817e86a4cf42ddc3af482417dfc668b3c4/src/rtmessage/rtMessageHeader.c#L78
- `T3`: https://github.com/rdkcentral/rbus/blob/6455fb817e86a4cf42ddc3af482417dfc668b3c4/src/rtmessage/rtMessageHeader.c#L79
- `T4`: https://github.com/rdkcentral/rbus/blob/6455fb817e86a4cf42ddc3af482417dfc668b3c4/src/rtmessage/rtMessageHeader.c#L80

**Comment by schmidtw** [comment]
Also encoding of the string length is inconsistent with the decoding of string length:
https://github.com/rdkcentral/rbus/blob/6455fb817e86a4cf42ddc3af482417dfc668b3c4/src/rtmessage/rtEncoder.c#L54

**Comment by karuna2git** [comment]
Hi @schmidtw,
The method name says it as Int32 but internally its the 4 bytes that we manage.
That was the reason `rtMessageHeader_Decode()`  worked so far.

But I agree, we must have right Encoding and Decoding APIs used to have proper readability and understanding.

We addressed it under https://github.com/rdkcentral/rbus/pull/140
